import type { Metadata } from 'next';
import './globals.css';
import ThemeProvider from './provider';
import { MainLayout } from '@/layout/MainLayout';
import { Locale, i18n } from '@/i18n.config';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  return (
    <html lang={locale}>
      <body className="font-SFProDisplay">
        <ThemeProvider>
          <MainLayout locale={locale}>{children}</MainLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
